

services:
  db:
    image: mysql:8.0
    container_name: focus-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./server/database.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: focus-app
    restart: always
    ports:
      - "3003:3002"
      - "5002:5001"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes: # dev only
      - ./src:/app/src
      - ./server:/app/server

volumes:
  db_data:
